# spajai's standard Travis CI config for Perl 5 modules
# https://github.com/briandfoy/brians_perl_modules_travis_config
# This file is licensed under the MIT license

sudo: false

language: perl
perl:
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"
    - "5.22"
    - "5.24"
    - "5.26"

os:
  - linux
  - osx
  
matrix:
    allow_failures:
        - os: osx
