---
abstract: 'The great new 2018 Yahoo::Weather::Api '
author:
  - 'Sushrut Pajai <spajai@cpan.org>'
build_requires:
  JSON: '2.0'
  JSON::Parse: '0'
  Test::More: '0'
  URL::Builder: '0.06'
  XML::LibXML: '0'
  XML::Validate: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150001'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Yahoo-Weather-Api
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  LWP::UserAgent: '0'
  URL::Builder: '0.06'
  perl: '5.006'
version: '1.10'
